apiVersion: batch/v1
kind: Job
metadata:
  name: secret-cleanup-job
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: secret-cleanup
    spec:
      serviceAccountName: secret-manager-sa 
      containers:
      - name: secret-manager
        image: bitnami/kubectl:latest
        command: ["kubectl", "delete", "secrets", "-n", "cattle-impersonation-system", "--all"]
      restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-manager-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-manager-binding
subjects:
- kind: ServiceAccount
  name: secret-manager-sa
  namespace: default 
roleRef:
  kind: ClusterRole
  name: secret-manager-role
  apiGroup: rbac.authorization.k8s.io

