apiVersion: batch/v1
kind: CronJob
metadata:
  name: secret-manager-cron
spec:
  schedule: "0 0 * * *"  # Cron schedule in cron format (here, it runs daily at midnight)
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: secret-manager-cron-sa
          containers:
          - name: secret-manager-cron
            image: bitnami/kubectl:latest  # Replace with private repo container image
            command: ["kubectl", "delete", "secrets", "-n", "cattle-impersonation-system", "--all"]
          restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager-cron-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-manager-cron-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-manager-cron-binding
subjects:
- kind: ServiceAccount
  name: secret-manager-cron-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: secret-manager-cron-role
  apiGroup: rbac.authorization.k8s.io